# Generated by Django 3.1.7 on 2022-06-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
